### ISSUE TITLE
Nodes with more features than NODE_NETWORK get a "Services index" of 0.0 in Leaderboard

### ISSUE THREAD

**Issue by runeksvendsen** [ayeowch/bitnodes#10]
Just thought I would report this since I'm not sure this is intended.

My node is a NODE_NETWORK node as well as NODE_GETUTXOS node (`services` field in `version` message equals 3)

This is my node: https://getaddr.bitnodes.io/nodes/leaderboard/?q=212.60.121.120

As you can see the SI value is "-". Should it not be 1.0, as the node *is* a NODE_NETWORK node, although it's also a NODE_GETUTXOS node?

**Comment by ayeowch** [comment]
Thanks for reporting this! At the moment, I am enumerating only the services declared (nServices flags) in the reference client. It looks like NODE_GETUTXOS is currently declared only in bitcoinj. Did you have to modify your reference client in anyway to get it to declare its services as NODE_NETWORK + NODE_GETUTXOS?

**Comment by ayeowch** [comment]
I am assuming you are running Bitcoin XT?

**Comment by runeksvendsen** [comment]
Hi Addy

Yes, I'm running Bitcoin XT.

**Comment by ayeowch** [comment]
Cool, that make sense now. I will update the site to support enumeration of NODE_GETUTXOS as well tomorrow.

**Comment by runeksvendsen** [comment]
Great! Thanks a lot.

**Comment by ayeowch** [comment]
No worries! I am glad to have someone brought this up. Nodes with services=3 (NODE_NETWORK, NODE_GETUTXOS) are listed properly now: https://getaddr.bitnodes.io/nodes/?q=NODE_GETUTXOS. The next peer index update will reflect this change accordingly.

**Comment by ayeowch** [comment]
Fixed: https://getaddr.bitnodes.io/nodes/leaderboard/?q=212.60.121.120
