### ISSUE TITLE
"Check Node" reports node is up, but "Node Status" says it isn't.

### ISSUE THREAD

**Issue by Geremia** [ayeowch/bitnodes#13]
Clicking the "Check Node" button on the bottom of the page reports that the node associated with this IP address is up; however, at the top of the page, "Node Status" says it isn't.

**Comment by ayeowch** [comment]
"Check Node" connects directly to your node since your IP is known. The "Node Status" page uses crawl data from the crawler which starts from a list of known nodes. It is possible your node is not well connected at the moment. Check how many peers you connected to based on the getpeerinfo output.

**Comment by Geremia** [comment]
Yes, I have had very few incoming connections recently due to a router issue that brought the node down a few days ago. You're probably right that my node isn't well connected now.

**Comment by Geremia** [comment]
Well, it's been days now that the node has been up without interruption, yet the page still thinks it's down…

**Comment by ayeowch** [comment]
How many connections do you have now?

**Comment by Geremia** [comment]
It has about 3-4 inbound connections now, and I've had 732 MB sent.

**Comment by ayeowch** [comment]
That's an indication of the node not being well connected. Usually your node will be crawled within minutes once it has more than 8 peers. Another reason the crawler is not able to find you is due to change of IP if you are using dynamically allocated IP by your ISP.

**Comment by Geremia** [comment]
Do the node have to accept UDP packets? Currently, I'm only accepting TCP packets.

**Comment by ayeowch** [comment]
No. Only TCP is required.

**Comment by Geremia** [comment]
I'm running the node now on a different network (on even supporting IPv6), and I get the same issue.

I'm thinking it may have something to do with my running bitcoin-qt with a Tor proxy, although I'm explicitly supplying the "--listen" flag to bitcoin-qt…

**Comment by Geremia** [comment]
Perhaps the network just doesn't have any need for another node in my area?

**Comment by ayeowch** [comment]
As long as the node has --listen and it is reachable by other peers, it should be on Bitnodes after being online for few minutes. Are you able to run your client without going Tor proxy to see if that makes it appear as UP on Bitnodes?

**Comment by Geremia** [comment]
It has appeared as up on Bitnodes even through Tor, when a couple IPv6 clients were connected to the node. Now, however, Bitnodes says it's down. Thus, going proxy through Tor or not doesn't seem to change things.

**Comment by Geremia** [comment]
It has appeared as up on Bitnodes even through Tor, when a couple IPv6 clients were connected to the node. Now, however, Bitnodes says it's down. Thus, going proxy through Tor or not doesn't seem to change things.

**Comment by Geremia** [comment]
You could try adding the node yourself and see if it works:
IPv4: 68.3.244.232:8333
IPv6: [2001:470:1f19:7e:290:f5ff:febe:832d]:8333

**Comment by Geremia** [comment]
It seems the Bitcoin network just isn't discovering my node (or perhaps it doesn't need it in my area?).

**Comment by ayeowch** [comment]
Whenever Bitnodes says DOWN, can you help check how many connections (inbound + outbound) do you have?

Also, it looks like you are behind dynamically allocated IP. Is that correct? If this is the case, it is possible your node changes its IP before it is able to establish itself among peers in the network.

**Comment by ayeowch** [comment]
The issue here may be related to https://github.com/bitcoin/bitcoin/issues/48

**Comment by ayeowch** [comment]
Fixed with https://github.com/ayeowch/bitnodes/commit/802f3b678db86fa914600191239b9e735549ad47

**Comment by Geremia** [comment]
Well, today I have 8 incoming and 8 outgoing nodes! I think it just took my node a few days of using the same IPv6 and IPv4 addresses before the network considered it stable.
