### ISSUE TITLE
Longer historical view

### ISSUE THREAD

**Issue by btcdrak** [ayeowch/bitnodes#14]
Now that the site has been collecting data for a long time, do you think you could add more views, like `180d` and `1y`, maybe even `All`?

**Comment by ayeowch** [comment]
Thanks for the request. I am planning to make available 1-year chart by the end of this month.

**Comment by ayeowch** [comment]
1-year charts are available now from https://getaddr.bitnodes.io/dashboard/?days=365

**Comment by zsharifian** [comment]
Thanks for your very good work
1. Is it possible to access the block propagation delay (not daily but for each block) during one or more months? In fact, the charts provide information for a day or month with just one value.

2. In addition, is it possible to access 90% or more for block propagation?

by regards
