### ISSUE TITLE
Node activation via API

### ISSUE THREAD

**Issue by jaltek** [ayeowch/bitnodes#15]
Hi,

is there a way to _activate_ a node via the API?
Or what are the alternatives to use the Bitnodes page?

The API states

Set Bitcoin address for an activated node. Node must be activated separately, **i.e.** from ```https://getaddr.bitnodes.io/nodes/<ADDRESS>-<PORT>/```, before it can be updated using this endpoint.

**Comment by ayeowch** [comment]
The activation must be done on the website by browsing through the list of nodes from https://getaddr.bitnodes.io/nodes/.
