### ISSUE TITLE
Leaderboard contains non-functional nodes

### ISSUE THREAD

**Issue by rebroad** [ayeowch/bitnodes#20]
The leaderboard is including nodes that have not been online for almost a month.

**Comment by ayeowch** [comment]
@rebroad Thanks for reporting this. Can you point me to one of these nodes?

**Comment by rebroad** [comment]
https://bitnodes.21.co/nodes/leaderboard/?q=satushi will show some of those nodes. This output also shows another issue, which is that some nodes show as simply ":8333".

**Comment by ayeowch** [comment]
https://bitnodes.21.co/nodes/223.206.70.202-8333/ was indeed down for a while. Bitnodes was configured to delete stale nodes after much later. I have just updated it to delete stale nodes older than 7 days.

**Comment by rebroad** [comment]
The first link above is different in that the node that was down since 27th September is no longer showed. However, there are two nodes showing that have DU/DL/WU/WL of zero. Perhaps they will disappear within the next 24 hours though.

**Comment by ayeowch** [comment]
The node with ":8333" had custom hostname set but it is no longer resolvable and causes the node to have empty IP address set in the DB; I have removed 2 such nodes from the DB.
