### ISSUE TITLE
WL&WU showing as zero for some nodes

### ISSUE THREAD

**Issue by rebroad** [ayeowch/bitnodes#21]
https://bitnodes.21.co/nodes/leaderboard/?q=satushi

Shows one of these nodes as having WU and WL as zero, even though it's been up for over 24 hours. This seems incorrect...

**Comment by ayeowch** [comment]
The weekly latency index requires at least (168 ticks - 10%), i.e. ~151 ticks from the node before it will be calculated. The weekly latency chart is a 7-day series with 1 tick = 1 hour.

Similarly, for daily latency index, (96 ticks - 10%), i.e. 86 ticks is needed from the node before it will be calculated. The daily latency chart is a 1-day series with 1 tick = 15 minutes.

**Comment by rebroad** [comment]
@ayeowch I'm pretty sure there is a bug here. One of my nodes (based on IP address) has been up for weeks (virginbitcoin.ddns.net), yet is getting 0.0 for WL&WU.

**Comment by ayeowch** [comment]
@rebroad It looks like virginbitcoin.ddns.net node status was activated on the website about 6 days ago. Let's give it another day or or two for the WL & WU to show up.

**Comment by ayeowch** [comment]
@rebroad I'm closing this as WL & WU for virginbitcoin.ddns.net are populated now: https://bitnodes.21.co/nodes/leaderboard/?q=satushi
