### ISSUE TITLE
question: testnet leaderboard

### ISSUE THREAD

**Issue by rebroad** [ayeowch/bitnodes#22]
I notice there are bitnode probes running on testnet - is there a website to see the results from these probes?

**Comment by ayeowch** [comment]
The crawler (crawl.py) is currently running in testnet3 to only take snapshot of the network for seeding purpose. ping.py and other part of the project required to gather data for website such as https://bitnodes.21.co is not running in testnet3.

**Comment by rebroad** [comment]
Thanks.. hope it was ok to raise an issue for such a question.
