### ISSUE TITLE
THIN service bit not displayed

### ISSUE THREAD

**Issue by rebroad** [ayeowch/bitnodes#23]
When viewing a node's services, only NODE_NETWORK, NODE_BLOOM and NODE_WITNESS seem to be displayed. NODE_XTHIN currently is not.

Also, it would be great if it was possible to search for nodes based on service bit.... :)

**Comment by ayeowch** [comment]
@rebroad I'll look into adding NODE_XTHIN. Thanks for mentioning it! Search currently allows e.g. https://bitnodes.21.co/nodes/?q=NODE_WITNESS

**Comment by ayeowch** [comment]
@rebroad Just added NODE_XTHIN display. It doesn't look like there is a reachable node with this bit set though?

**Comment by ayeowch** [comment]
@rebroad NODE_XTHIN nodes are shown now at bitnodes.21.co/nodes/?q=NODE_XTHIN
