### ISSUE TITLE
BU nodes not correctly reported on the "User Agents" tab

### ISSUE THREAD

**Issue by gandrewstone** [ayeowch/bitnodes#26]
If you look at the user agents tab its showing "/BitcoinUnlimited:1.0.1.3/" as 359 nodes.  Now click on that string so that it is run as a search in the search box.  I see 515 nodes.

https://www.supload.com/SkMwxw9ag

**Comment by ayeowch** [comment]
Thanks for the report!

The counts for the user agents in the table are fixed now by counting major UA in the user agent string.

However, the table may still show BitcoinUnlimited:1.0.1.3 as 382 (counted using major UA) but when clicked, the nodes list may show 527 (counted using anything that matches the search string) nodes. This mismatch is an issue only for this particular search string as there are several nodes using non-standard user agent, i.e. https://bitnodes.21.co/nodes/?q=btcpop

**Comment by gandrewstone** [comment]
BU allows a user to add comments his UA, so I think that a more accurate reporting would count any UA string with "BitcoinUnlimited" in it.
