### ISSUE TITLE
start.sh refers to nonexistent conf files

### ISSUE THREAD

**Issue by matthewleon** [ayeowch/bitnodes#30]
The culprit appears to be a recent change to `start.sh`: https://github.com/ayeowch/bitnodes/commit/5e7202910d59ab910dd2291a8def9be0d3604827#diff-d0b2ef35f4d7cb0284dd5cf566b62f51

For example, `crawl.f9beb4d9.conf` does not exist.

Perhaps the relevant `conf` files just need to be `git add`ed?

**Comment by ayeowch** [comment]
The crawl.MAGIC_NUMBER.conf file must be created manually from the sample crawl.conf.default.

**Comment by paranoid945** [comment]
How to create this file manually? I didn't find it in https://github.com/ayeowch/bitnodes/wiki/Provisioning-Bitcoin-Network-Crawler

**Comment by ayeowch** [comment]
See the sample conf files in https://github.com/ayeowch/bitnodes/tree/master/conf
