### ISSUE TITLE
Installation and Usage guide

### ISSUE THREAD

**Issue by varun-v-deshpande** [ayeowch/bitnodes#31]
Hi,

I am new to bitnodes. I want to map bitcoin topology. I mean from the API, I can just get the total nodes. I want to know how they are connected to each other. I mean I want to reproduce the connection graph of bitcoin.

Could anyone can guide me on how can I do that ? Also, How to install bitnodes to work on it ?

**Comment by ayeowch** [comment]
Currently, it is not possible to map the connection between nodes with Bitnodes.
https://cs.umd.edu/projects/coinscope/coinscope.pdf may be of interest to you.
