### ISSUE TITLE
Newer Bitcoin Cash nodes use a different Network magic

### ISSUE THREAD

**Issue by cculianu** [ayeowch/bitnodes#32]
Up until today the crawler worked for the Bitcoin Cash network so that people could see Bitcoin Cash as well as Bitcoin nodes.

Bitcoin Cash's latest node software has transitioned over to using a different message magic number now, so as to be totally separate from Satoshi nodes.

As of today all new Bitcoin ABC 0.16.2 nodes will no longer be seen by your crawler.

Are there plans to fix this and add support back for NODE_CASH nodes?

I can also submit a PR to fix this if you like.

**Comment by Klakurka** [comment]
Yeah, could you do this? We'd definitely merge it into ours for public display.

**Comment by ayeowch** [comment]
The crawler supports this since https://github.com/ayeowch/bitnodes/commit/5e7202910d59ab910dd2291a8def9be0d3604827

**Comment by garceri** [comment]
The crawler on yoursite bitnodes.earn.com doesn't support ABC nodes >0.16.1. Take a look at the sheea number of nodes for each version. There are 600+ 0.16.1 nodes and just 2 running 0.16.2 and 0 running 0.17. Please Fix ASAP.

**Comment by ayeowch** [comment]
@garceri the crawler supports and is currently crawling ABC nodes >0.16.1 but they are not currently listed/supported on the website.
