### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by s-tikhomirov** [ayeowch/bitnodes#35]
It would be nice to include at least a short guide on how to use this tool with some examples. Assume I want to get the latest snapshot of Bitcoin peers: which file do I run? Do I have to manually configure anything? Where do I expect to get the results? What do I do if I want to get the same stats for another network, say, the Bitcoin testnet?

Sure, one can figure out the answers to these questions by reading the source code, but even a short manual would greatly speed up this process.

**Comment by s-tikhomirov** [comment]
@ayeowch why close? Do you think such guide will not be useful? That is not to say I expect you to implement this, but an open issue might encourage members of the community (myself included) to contribute.

**Comment by rromanchuk** [comment]
@s-tikhomirov i will work on a guide, but it's way beyond the scope of the software itself.
