### ISSUE TITLE
Bi always zero

### ISSUE THREAD

**Issue by gustavonalle** [ayeowch/bitnodes#37]
According to the leaderboard ranking rules, Bi is
```
BI = Block index
    BI = 1.0 if valid block is returned in response to getdata request, 0.0 if otherwise
```

But for my node this value is always zero. Could you clarify how is it calculated and how can I troubleshoot why is it always zero?

Thanks!

**Comment by ayeowch** [comment]
@gustavonalle What is your node's IP address?
