### ISSUE TITLE
no support for Bitcoin ABC 0.17.1？

### ISSUE THREAD

**Issue by user5111** [ayeowch/bitnodes#38]
i use ’https://bitnodes.earn.com/api/v1/snapshots/latest/‘ to download the node's informations for analysis
. but i can'nt find the node with USER AGENTS: Bitcoin ABC 0.17.1

**Comment by ayeowch** [comment]
@user5111 the crawler supports and is currently crawling ABC nodes >0.16.1 but they are not currently listed/supported on the website except via the seeder described in https://bitnodes.earn.com/api/#dns-seeder.
