### ISSUE TITLE
[Error] Getting invalid TCPdump header when running pcap

### ISSUE THREAD

**Issue by Kulgar** [ayeowch/bitnodes#39]
Hello, 

I'm getting this error while running the pcap python process:

```
Traceback (most recent call last):
  File "pcap.py", line 319, in <module>
    sys.exit(main(sys.argv))
  File "pcap.py", line 313, in main
    cron()
  File "pcap.py", line 257, in cron
    cache.cache_messages()
  File "pcap.py", line 99, in cache_messages
    self.extract_streams()
  File "pcap.py", line 136, in extract_streams
    pcap_reader = dpkt.pcap.Reader(pcap_file)
  File "/path-to-home/.virtualenvs/bitnodes/local/lib/python2.7/site-packages/dpkt/pcap.py", line 257, in __init__
    raise ValueError('invalid tcpdump header')
ValueError: invalid tcpdump header
```

Did you ever encounter that error? And do you have any clues on how to solve it?

Thanks :)

**Comment by ayeowch** [comment]
@Kulgar Can you upload the .pcap file that causes the error above?

**Comment by Kulgar** [comment]
Sure thing :) 

[1530680517.eth0.pcap.txt](https://github.com/ayeowch/bitnodes/files/2210224/1530680517.eth0.pcap.txt)

I had to rename it (added txt extension) because Github isn't supporting "pcap" extension for uploads. 

While searching the web about this error I found this discussion: https://stackoverflow.com/questions/23523524/dpkt-invalid-tcpdump-header-error

I think that is what happens here, but I am not sure.

**Comment by ayeowch** [comment]
How was 1530680517.eth0.pcap.txt generated? It does not look like pcap file.

**Comment by Kulgar** [comment]
Well I used the commands from the wiki: 

``` 
sudo tcpdump -i eth0 -w %s.eth0.pcap -v -n -G 2 -B 65536 -Z [USERNAME] 'tcp and not src host [IP_ADDRESS] and not src host [IPV6_ADDRESS]' > eth0 2>&1 &
sudo tcpdump -i lo -w %s.lo.pcap -v -n -G 2 -B 65536 -Z [USERNAME] 'tcp and port 9050' > lo 2>&1 &
```

How can you tell that it is not a pcap file?
And why would these commands generate a none pcap file?

**Comment by ayeowch** [comment]
@Kulgar What OS are you running the command on?

**Comment by Kulgar** [comment]
Ubuntu 18.04 Bionic

**Comment by Kulgar** [comment]
Yeah I have the same version. 

That's strange, I was trying to reproduce the bug by restarting all the processes... But it seems to work properly now.

Well... I hope I did not bother you too much. 
If it happens again I'll send you the faulty pcap file by mail. 

Thanks for your patience and kindness
