### ISSUE TITLE
Version number causing installation problem on CentOS 7

### ISSUE THREAD

**Issue by mysticaltech** [ayeowch/bitnodes#42]
Hello, so I'm trying to install on CentOS 7 directly from:

`curl https://bitnodes.earn.com/install-full-node.sh | sh`

I'm getting the following error (last line):

```
Downloading Bitcoin Core binaries..
Checksum passed: bitcoin-0.17.0.1.tar.gz (6ccc675ee91522eee5785457e922d8a155e4eb7d5524bd130eb0ef0f0c4a6008)
Signature passed: Signed checksum.asc verified successfully!

Installing Bitcoin Core v0.17.0.1
Cannot find files to install.
```

When I ls bitcoin-core I get:

```
total 0
drwxrwxr-x 2 gold gold  6 Nov 28 22:24 bin
drwxr-xr-x 6 gold gold 56 Oct 26 11:53 bitcoin-0.17.0
```

You see the problem? The version number somehow is missing a 'decimal' if we could call it that. 

Going to try to hack the script manually for my own install case, but would be cool to fix that for other CentOS 7 users.

Cheers and keep up the good work!

**Comment by mysticaltech** [comment]
For other like me, I was able to move on with the install doing a simple mv and repeating the install:
`mv bitcoin-core/bitcoin-0.17.0 bitcoin-core/bitcoin-0.17.0.1`

**Comment by ayeowch** [comment]
Good catch. The script is fixed now.
