### ISSUE TITLE
Trouble activating a new Onion node

### ISSUE THREAD

**Issue by brianddk** [ayeowch/bitnodes#46]
Is there a latency between a node coming online and it being reachable by your scripts.  I'm currently running an onion node and can verify that I'm receiving inbound connections.  I can also verify the node is reachable using bsd-netcat:

```
nc -v -n -z -X 5 -x 127.0.0.1:9050 somebtconionnode.onion 8333
```

But when I try to activate `somebtconionnode.onion:8333` (made up name) through https://bitnodes.io/nodes/somebtconionnode.onion-8333/ it never transitions from `DOWN` to `UP`.  What's more, I'm connected (outgoing) to a half dozen onion nodes.  Since I'm connected to them, they must be reachable for inbound connections on the network.  If I try activating those nodes, I get the same results as my node.

Do I need to have my onion up for 24 hours or something before it can be activated on bitnodes.io?  Is there anything else I should do?

I've also included my actual node info in an attached PGP file for @ayeowch

[msg-ayeowch.asc.gz](https://github.com/ayeowch/bitnodes/files/5197593/msg-ayeowch.asc.gz)

**Comment by brianddk** [comment]
I just now restarted my nodes with the following added to `bitcoin.conf`:

```
[main]
addnode=88.99.167.175:8333
addnode=88.99.167.186:8333
addnode=[2a01:4f8:10a:37ee::2]:8333

[test]
addnode=88.99.167.175:18333
addnode=88.99.167.186:18333
addnode=[2a01:4f8:10a:37ee::2]:18333
```

Hopefully this will put me in the crawler's peer list.  If you have the onion address / port for the crawler I could add it as well.  Would be nice to have that on your page footer along with the ipv4 / ipv6 addresses.

**Comment by ayeowch** [comment]
The crawler has been running into issue connecting to onion nodes since Sep 6.

**Comment by brianddk** [comment]
@ayeowch would it help if I connected my node (`addnode`)  to the onion address of the crawler.  All I found on the site footer were the ipv4 and ipv6 addresses above.

**Comment by ayeowch** [comment]
@brianddk The crawler connects outbound only. IPv4 and IPv6 addresses published on the website is mostly informational to let node operators know that the connection originates from Bitnodes.

**Comment by ayeowch** [comment]
This should be fixed now with https://github.com/ayeowch/bitnodes/commit/8d42c7ad4804b539a9af2619c8e8bed90dcb5a62
