### ISSUE TITLE
Tor V3

### ISSUE THREAD

**Issue by Covalent5** [ayeowch/bitnodes#47]
Just updated to Bitcoin Core 0.21.0 and I run it behind Tor. Now with the Tor V3 support, my node is not visible on bitnodes. Am I correct into thinking it's not yet supported?￼

**Comment by ayeowch** [comment]
Bitnodes does not yet support Tor v3. Will keep this ticket open until the support is live.

**Comment by ayeowch** [comment]
Added Tor V3 supported via https://github.com/ayeowch/bitnodes/commit/a347c758ce8d7879f436bf0614237c31ce993489

**Comment by micressor** [comment]
My Core 0.21.0 with Tor V3 seems not to work.
The test connection with .onion address (Join the network -> check node) success.
But it never get a up status from bitnodes.

**Comment by Covalent5** [comment]
Same here.

**Comment by gallizoltan** [comment]
@micressor @Covalent5 What happens if you check your node on bitnodes and hit "ACTIVATE NODE STATUS"? The link is something like this:
https://bitnodes.io/nodes/{your_torv3_address}-8333/
It may take some time, but this works for me.

**Comment by Covalent5** [comment]
> @micressor @Covalent5 What happens if you check your node on bitnodes and hit "ACTIVATE NODE STATUS"? The link is something like this:
> 
> https://bitnodes.io/nodes/{your_torv3_address}-8333/
> 
> It may take some time, but this works for me.
> 
> 

It says pending.

**Comment by micressor** [comment]
> https://bitnodes.io/nodes/{your_torv3_address}-8333/

It still saying down.
At the same time test connection with .onion address (Join the network -> check node) success.

**Comment by micressor** [comment]
> It still saying down.
> At the same time test connection with .onion address (Join the network -> check node) success.

Seems to work since a day. Nothing changed on my side. Strange, but ok.

**Comment by micressor** [comment]
I think tor V3 address monitoring of bitnodes does not really work stable at the moment.

Checknode API call does work perfect

```
curl -H "Accept: application/json; indent=4" -d "address=torv3.onion&port=8333" https://bitnodes.io/api/v1/checknode/
{
    "user_agent": "/Satoshi:0.21.0/",
    "port": 8333,
    "address": "torv3.onion"
}
```
But nodes API call says:
```
curl -H "Accept: application/json; indent=4" https://bitnodes.io/api/v1/nodes/torv3.onion-8333/
{
    "hostname": "",
    "address": "torv3.onion",
    "status": "DOWN",
[...]
```
Currently it seems that bitnodes has only a handful of tor V3 onion addresses listed. Maybe the problem of stability has not yet been recognized. Can other V3 .onion operators confirm this?
