### ISSUE TITLE
[HELP] can you explain how to configure my own custom config?

### ISSUE THREAD

**Issue by master-davidlee** [ayeowch/bitnodes#53]
start.sh shell needs custom config like crawl.MAGIC_NUMBER.conf. Can you tell me how to do that or explain every part?

**Comment by ayeowch** [comment]
MAGIC_NUMBER should be replaced with f9beb4d9 for Bitcoin mainnet: https://developer.bitcoin.org/reference/p2p_networking.html#constants-and-defaults
