### ISSUE TITLE
Break down Nodes by full user-agent?

### ISSUE THREAD

**Issue by jstefanop** [ayeowch/bitnodes#54]
We just started shipping our decentralized home mining/node solution for consumers (futurebit.io) and will soon have thousands of nodes coming online from these devices. Would be awesome if there is an option to filter through custom flagged user agent strings on top of the version agent. I know blockchair filters through the full user agent string but their crawler does not seem to be as comprehensive as yours.

**Comment by ayeowch** [comment]
The search page, e.g. https://bitnodes.io/nodes/?q=futurebit, now returns the percentage value (of network snapshot) in addition to the node count:

![image](https://user-images.githubusercontent.com/500869/122837839-29550880-d338-11eb-9839-f25b09bbfc0f.png)

![image](https://user-images.githubusercontent.com/500869/122837792-10e4ee00-d338-11eb-83ad-a05282dc15ea.png)

**Comment by jstefanop** [comment]
@ayeowch thanks! Anyway to filter the live map and network map the same way so only specific user agent strings show up? BTW would love to donate to your project.
