### ISSUE TITLE
install-full-node script is outdated

### ISSUE THREAD

**Issue by danger89** [ayeowch/bitnodes#57]
Hi,

Your `install-full-node.sh` script is installing an old version of the bitcoin core. The latest version is `22.0`

Regards,
Melroy

**Comment by ayeowch** [comment]
Thanks for letting me know. It should be up-to-date now.

**Comment by danger89** [comment]
⚠️  No no.. Its' 22.0... not 0.22 ⚠️ .. yea, they removed the leading zero. Take a closer look.

**Comment by ayeowch** [comment]
Opps :sweat: Reuploaded with the corrected version and thanks again!

**Comment by danger89** [comment]
Yeah, now its good ;)
