### ISSUE TITLE
Feature request: Enable connection to Zerotier Earth enabled nodes

### ISSUE THREAD

**Issue by rebroad** [ayeowch/bitnodes#58]
There is a network available which provides access to additional bitcoin nodes, with better latency than Tor or I2P, which I have been running my nodes on for several years now. I am curious to know if there are many others.

Might it be possible to enable this network interface on your crawler to find out?

E.g. I have 2 nodes running, one on 29.34.239.165:8333 and one on 28.183.108.93:8333 (the entire 28.0.0.0/8 and 29.0.0.0/8 ranges are used by ZeroTier Earth).

**Comment by ayeowch** [comment]
There is no plan to support networks other than the current mainnet on IPv4/v6 and Tor v2/v3.
