### ISSUE TITLE
Is Bitnodes mirrored via Onion or I2P?

### ISSUE THREAD

**Issue by brianddk** [ayeowch/bitnodes#64]
[Bitnodes is down](https://archive.ph/4uF0l/image), or at least was at the time of this posting.

Are there any mirrors of `bitnodes.io` exposed as an Onion or I2P site to use while the IPv4 and IPv6 versions are down?

**Comment by ayeowch** [comment]
This site is up now. It was down for hard drive maintenance. Unfortunately, there is no mirror of the site atm.

**Comment by brianddk** [comment]
> This site is up now. It was down for hard drive maintenance. Unfortunately, there is no mirror of the site atm.

Thx
