### ISSUE TITLE
Bitnodes reporting inflated IPV4 nodes

### ISSUE THREAD

**Issue by Fiach-Dubh** [ayeowch/bitnodes#74]
https://bitnodes.io/nodes/all/#global-bitcoin-nodes

is there a bitnodes data issue? according to luke-jr and lopp these numbers are not accurate. 

https://twitter.com/lopp/status/1540712512521285632

**Comment by ayeowch** [comment]
The inflated numbers from the past couple of days is due to fake IPv4 addresses being returned by addr responses from some peers that Bitnodes crawler is connected to. I will look into a fix and revise the data in https://bitnodes.io/nodes/all/#global-bitcoin-nodes

**Comment by Fiach-Dubh** [comment]
Thank You
