### ISSUE TITLE
Checksum failed

### ISSUE THREAD

**Issue by stevebanik** [ayeowch/bitnodes#75]
After running:

curl https://bitnodes.io/install-full-node.sh | sh

this error occurs:

Downloading Bitcoin Core binaries..
grep: checksum.asc: No such file or directory
Checksum failed: bitcoin-24.0.tar.gz (e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855). Please rerun this script to download and validate the binaries again.

macOS Monterey 12.6.1

I ran it again, and the same error appeared.

**Comment by ayeowch** [comment]
@stevebanik Are you able to access https://bitcoincore.org/bin/bitcoin-core-24.0/SHA256SUMS?

**Comment by ayeowch** [comment]
@stevebanik Also, try both of these and see if you get error:
```
wget -q "https://bitcoincore.org/bin/bitcoin-core-24.0/SHA256SUMS" -O checksum.asc
curl -s "https://bitcoincore.org/bin/bitcoin-core-24.0/SHA256SUMS" -o checksum.asc
```
