### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by Gusfzzm** [ayeowch/bitnodes#82]
I would like to know how to run this code. Whenever I click run the following status appears. It doesn't run.
![H3CUYD18 UR@D$YB`19GSWL](https://github.com/ayeowch/bitnodes/assets/136805453/d9d2cd32-4cfc-4731-bfba-d0f10a53cf6c)

**Comment by ayeowch** [comment]
The crawler works on Linux only.
Sample provisioning steps are documented in https://github.com/ayeowch/bitnodes/wiki/Provisioning-Bitcoin-Network-Crawler

**Comment by Gusfzzm** [comment]
I'm running this code on a Linux system today. Follow the README step by step. But I don't know where the result exists at the end of the pytest run or there is no result? If I want to run the code locally to get data like the one shown on the website, how do I go about it?
<img width="630" alt="bb7a51f95e10677994c0ac0799a9fa7" src="https://github.com/ayeowch/bitnodes/assets/136805453/7bbb4c9d-46bb-40a0-b42e-5e7243c4f1ca">
<img width="586" alt="dc8b3c5bd79b941edaf3e5328191ed0" src="https://github.com/ayeowch/bitnodes/assets/136805453/c881bec1-9f33-4759-a035-ac2edcf597d8">

**Comment by ayeowch** [comment]
The pytest is meant for running the tests only. For actual crawling, you should use the start.sh as per https://github.com/ayeowch/bitnodes/wiki/Provisioning-Bitcoin-Network-Crawler. All data are stored in data directory.

bitnodes.io does a lot of data post processing separately to make them presentable on the website and API (https://bitnodes.io/api/)

**Comment by Gusfzzm** [comment]
Dear author, I'm sorry to bother you again. I would like to ask about this first command, is it to create a new server? If I already have a Linux server do I need to create another Herzner server?I get an error when I run this command on my own Linux server
<img width="684" alt="5b00e60ccfce614750b0e63a549617b" src="https://github.com/ayeowch/bitnodes/assets/136805453/7ea7f006-78b1-4adc-91af-355650f54008">

<img width="506" alt="1693385588888" src="https://github.com/ayeowch/bitnodes/assets/136805453/c9047b05-5684-4f95-88f4-561ab45ffe79">

**Comment by ayeowch** [comment]
The wiki is intended as guidelines. You can use your existing Linux machine with Redis installed.

Complete the setup in https://github.com/ayeowch/bitnodes#setup then review the *conf files (https://github.com/ayeowch/bitnodes/wiki/Provisioning-Bitcoin-Network-Crawler#launch-crawler) and update them accordingly before running start.sh.

The start.sh runs the full suite of programs for the crawler. You may also run just crawl.py and ping.py.

crawl.py takes a fresh network snapshot repeatedly (about every 5 minutes). ping.py keeps connections with nodes discovered by crawl.py.

resolve.py and export.py enumerate additional data (hostname, geoip) for all connected nodes.

seeder.py is intended only for use if you are running/operating a Bitcoin DNS seeder.

**Comment by Gusfzzm** [comment]
Thanks for the guidance, but I've run into some new problems. Very sorry about that. I would like to ask if this command is necessary, it forbids me to write when I operate in my system. And I would like to ask if this [MAXMIND_LICENSE_KEY] is copied directly or do I have to modify it before writing?
<img width="774" alt="80b8579198940cc1d2e8c5c303e93aa" src="https://github.com/ayeowch/bitnodes/assets/136805453/343441f4-7e64-4c34-9167-d15d679b4241">
<img width="273" alt="b14ecb1559433011e0a2633f97696f3" src="https://github.com/ayeowch/bitnodes/assets/136805453/f9b9bcde-6844-4b28-83b6-cd9739a0f410">

**Comment by ayeowch** [comment]
Replace `[MAXMIND_LICENSE_KEY]` with your Maxmind license key: https://support.maxmind.com/hc/en-us/articles/4407111582235-Generate-a-License-Key

**Comment by Gusfzzm** [comment]
When I get to this point, do I need to delete all the contents of the original file？
<img width="338" alt="1693472088881" src="https://github.com/ayeowch/bitnodes/assets/136805453/d362d910-44c6-47e4-92f8-793e89f204e3">
<img width="641" alt="1693472140442" src="https://github.com/ayeowch/bitnodes/assets/136805453/9d7855a0-6586-4524-ad6f-beebdb25ca0a">

**Comment by Gusfzzm** [comment]
Hi author, what is the purpose of the last two lines in the guide? Do this [INTERFACE] and [USERNAME] need to be replaced with something else respectively?
<img width="672" alt="1693472719404" src="https://github.com/ayeowch/bitnodes/assets/136805453/85128f4c-1242-47d9-89d2-28c6b2ce0ddd">
Also, when I run Crawl.py on its own, I find that it is missing a lot of modules, do I need to download additional ones myself?
