### ISSUE TITLE
Some nodes appear as down but they aren't

### ISSUE THREAD

**Issue by NicodemusFLT** [ayeowch/bitnodes#85]
Hi, I realize that a lot of nodes that are up appears down according to bitnodes.io , e.g. 50.30.36.140 

When you enter the IP in the JOIN THE NETWORK field and hit the CHECK NOTE button it appears online.

That does not change 10 minutes later to list the IP up. It still stays down. 

Why is that ?

**Comment by ayeowch** [comment]
@NicodemusFLT Thanks for the report. The connection attempt from [ping.py](https://github.com/ayeowch/bitnodes/blob/master/ping.py) is getting an error from the target host with error `(sink) Closing ('50.30.36.140', 8333) (('50.30.36.140', 8333) closed connection)`, this is usually because the target host has reached its max. connections. If you own the node, can you help confirm this is the case?

**Comment by NicodemusFLT** [comment]
Hi there .... thanks for getting back to me. It is indeed correct that all 39 connections, except for one (the 40th), are closed, which can also be seen at http://btc.x4a.net. However, the IP should not be displayed as down because it isn't. This was working fine 1 or 2 months ago, but then suddenly, the statistics show that the node is marked as down. Have you perhaps made any changes in this regard? It can also be seen in the CHECK NODE addition dialog that the feedback indicates that the node is reachable, regardless of the fact that all 39 slots have connections ...

 

Marty

 
 

Gesendet: Dienstag, 07. November 2023 um 09:53 Uhr
Von: "Addy Yeow" ***@***.***>
An: "ayeowch/bitnodes" ***@***.***>
Cc: "NicodemusFLT" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ayeowch/bitnodes] Some nodes appear as down but they aren't (Issue #85)


 

@NicodemusFLT Thanks for the report. The connection attempt from ping.py is getting an error from the target host with error (sink) Closing ('50.30.36.140', 8333) (('50.30.36.140', 8333) closed connection), this is usually because the target host has reached its max. connections. If you own the node, can you help confirm this is the case?

**Comment by ayeowch** [comment]
The `CHECK NODE` does not keep the connection alive and it comes from separate IP. It will attempt a handshake then disconnect immediately to release the connection and report the outcome of the handshake.

OTOH, ping.py attempts to keep the connection alive with your node. If the node has reached its max. connections, it will be tricky for ping.py to gain and keep a connection alive. A workaround would be to restart the node to release all connections and regain new connections including that from ping.py, or manually disconnect a few nodes to allow for the same.

**Comment by NicodemusFLT** [comment]
I appreciate the information, but it appears there's a discrepancy in the data accuracy. The current metrics seem to overlook operational full nodes due to false negatives and label nodes as unreachable when, in fact, they are simply at full connection capacity.

Hey Addy,

It's quite unexpected that the report/ticket was closed. I would recommend considering alternative methods to accurately reflect the status of available nodes.

The current statistics, as they stand, seem to be misleading and not representative of the actual network status.




Given that the metrics are utilized by the media, the community, and the cryptocurrency market, it's crucial to ensure that all statistics displayed on your platform bitnodes.io clearly indicate whether nodes at full capacity are represented. These nodes, which actually underscore the stability of the Bitcoin network, appear to be omitted from your site and potentially excluded from your data. Could you verify this?

The implication is that the Leaderboard might be providing a skewed perspective, conflating 'reachable' nodes with 'operating' ones, which is not necessarily accurate.

For the sake of clarity and transparency, an official statement on this matter for dissemination to the media would be highly appreciated.

Ultimately, the actual number of operational Bitcoin nodes outstrips the figures reported on bitnodes.io, right?

Restarting the node is not an acceptable workaround.

Greetz

Nico

btc.x4a.net








 

 
 

Gesendet: Dienstag, 07. November 2023 um 22:02 Uhr
Von: "Addy Yeow" ***@***.***>
An: "ayeowch/bitnodes" ***@***.***>
Cc: "NicodemusFLT" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ayeowch/bitnodes] Some nodes appear as down but they aren't (Issue #85)


 

The CHECK NODE does not keep the connection alive and it comes from separate IP. It will attempt a handshake then disconnect immediately to release the connection and report the outcome of the handshake.

OTOH, ping.py attempts to keep the connection alive with your node. If the node has reached its max. connections, it will be tricky for ping.py to gain and keep a connection alive. A workaround would be to restart the node to release all connections and regain new connections including that from ping.py, or manually disconnect a few nodes to allow for the same.

**Comment by ayeowch** [comment]
It's impossible to represent the exact network status due to this inherent limitation, i.e. we can't connect to a node that have reached its max. connections. I have used the word reachable on the website where applicable to indicate the metrics cover only the reachable nodes.

For global nodes metrics which unreachable nodes, https://bitnodes.io/nodes/all/ should be used instead. This is linked from the landing page.

**Comment by NicodemusFLT** [comment]
If that's the case, then so be it. Nonetheless, I appreciate the explanation. It seems there's nothing more to be done.

 

Thx and Cyaz

Nico

 
 

Gesendet: Mittwoch, 08. November 2023 um 21:17 Uhr
Von: "Addy Yeow" ***@***.***>
An: "ayeowch/bitnodes" ***@***.***>
Cc: "NicodemusFLT" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ayeowch/bitnodes] Some nodes appear as down but they aren't (Issue #85)


 

It's impossible to represent the exact network status due to this inherent limitation, i.e. we can't connect to a node that have reached its max. connections. I have used the word reachable on the website where applicable to indicate the metrics cover only the reachable nodes.

For global nodes metrics which unreachable nodes, https://bitnodes.io/nodes/all/ should be used instead. This is linked from the landing page.
