### ISSUE TITLE
Request was throttled

### ISSUE THREAD

**Issue by openchainio** [ayeowch/bitnodes#86]
i am facing this {"detail":"Request was throttled. Expected available in 63768 seconds."}  issue 
on this link https://bitnodes.io/api/v1/snapshots/latest/?field=top

**Comment by ayeowch** [comment]
This limit is documented in https://bitnodes.io/api/

**Comment by openchainio** [comment]
Sir can talk to you cause I am making a website for trading purpose I have also mail you but you don't reply
