### ISSUE TITLE
Add Bitcoin Knots option to install-full-node.sh 

### ISSUE THREAD

**Issue by GregTonoski** [ayeowch/bitnodes#87]
As a user, I want to choose installation of Bitcoin Knots In order to limit spam in Bitcoin.

Bitcoin Knots: https://bitcoinknots.org/

**Comment by ayeowch** [comment]
install-full-node.sh is not part of this repo which hosts the public crawler code.

**Comment by jesterhodl** [comment]
Is the script in any repo?

**Comment by jesterhodl** [comment]
Oh, it's private, thanks for the info
