### ISSUE TITLE
v2 Protocol

### ISSUE THREAD

**Issue by iotamega** [ayeowch/bitnodes#89]
Any intention on making the crawlers use V2 protocol so that other "bad nodes" will stop impersonating your crawlers?

**Comment by ayeowch** [comment]
[BIP0324](https://github.com/bitcoin/bips/blob/master/bip-0324.mediawiki) will be supported in the future on opt-in basis. Note that this does not stop others from running the crawler or modified copy of it.

**Comment by iotamega** [comment]
Awesome, yes, understood that others can run the code, that is awesome you provide the source.

Great to see the new V2 protocol will be supported as well, great move forward. Thank you for all that you do for the community.
